---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured            # Must match `--ds-name`
  namespace: kube-system # Must match `--ds-namespace`
spec:
  selector:
    matchLabels:
      name: kured
  updateStrategy:
   type: RollingUpdate
  template:
    metadata:
      labels:
        name: kured
    spec:
      serviceAccountName: kured
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostPID: true # Facilitate entering the host mount namespace via init
      restartPolicy: Always
      containers:
        - name: kured
          image: docker.io/weaveworks/kured-windows    # If you find yourself here
                                                    # wondering why there is no
                                                    # :latest tag on Docker Hub,
                                                    # see the FAQ in the README
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true # Give permission to nsenter /proc/1/ns/mnt
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KURED_NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KURED_POWERSHELL_USER_NAME
              value: "WINDOWS ADMIN USERNAME"
            - name: KURED_POWERSHELL_PASSWORD
              value: "INSERT PASSWORD HERE"
            - name: KUBE_CTL_PATH
              value: "C:\\KUBE_CTL_PATH"
          command: ["C:\\kured.exe"]
#         args:["--alert-filter-regexp=^RebootRequired$",
#            "--blocking-pod-selector=runtime=long,cost=expensive",
#            "--blocking-pod-selector=name=temperamental",
#            "--blocking-pod-selector=...",
#            "--ds-name=kured",
#            "--ds-namespace=kube-system",
#            "--lock-annotation=weave.works/kured-node-lock",
#            "--period=1h",
#            "--prometheus-url=http://prometheus.monitoring.svc.cluster.local",
#            "--reboot-sentinel=/var/run/reboot-required",
#            "--slack-hook-url=https://hooks.slack.com/...",
#            "--slack-username=prod"]
      nodeSelector:
        beta.kubernetes.io/os: windows